services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - '5432:5432'

  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app
    ports:
      - '8000:8000'
    depends_on:
      - db
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/__pycache__
      - /app/.pytest_cache
    environment:
      - PYTHONPATH=/app
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
